//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public ORDERS()
        {
            this.ORDER_DETAIL = new HashSet<ORDER_DETAIL>();
        }
    
        public int id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<System.DateTime> date_order_placed { get; set; }
        public Nullable<System.DateTime> date_order_paid { get; set; }
        public string shipping_method { get; set; }
        public string payment_method { get; set; }
        public string order_status { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL { get; set; }
    }
}
