//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        public PRODUCTS()
        {
            this.ORDER_DETAIL = new HashSet<ORDER_DETAIL>();
        }
    
        public int id { get; set; }
        public string product_name { get; set; }
        public string product_brand { get; set; }
        public string product_category { get; set; }
        public decimal product_price { get; set; }
        public Nullable<short> product_discount { get; set; }
        public string product_description { get; set; }
        public Nullable<short> profit_for_shop { get; set; }
        public int quantity_in_stock { get; set; }
        public int quantity_sold { get; set; }
    
        public virtual ICollection<ORDER_DETAIL> ORDER_DETAIL { get; set; }
    }
}
